#!/usr/bin/env python3
"""
make_figure.py -- generate the REAL Figure 1 for paper2 from the computed curves
(RESEARCH_LOG sec 38). Folds the q=5 Lagrangians to the pillowcase fundamental
domain [0,pi] x [0,2pi), splits polylines at fold/wrap discontinuities, and emits
TikZ paths, plus the nine generators and the support crossings s_A, s_B of the
bounding cochain. Output: ../paper2/fig_q5.tex (a TikZ *body*, \\input into the
figure environment). Replaces a hand-drawn schematic that had the red slope wrong
and the marked points off-curve.
"""
import math
from tangles import TAU, PI
from deform import build_geometry, bigon_matrix
from polygons import self_intersections_detailed
from earring import f8, P_point
from bigons import simplify, _tdist


def densify(poly, step=0.08):
    """Insert points so consecutive T^2 points are within `step` (short deltas)."""
    out = [poly[0]]
    for a, b in zip(poly, poly[1:]):
        dg = (b[0] - a[0] + PI) % TAU - PI
        dt = (b[1] - a[1] + PI) % TAU - PI
        n = max(1, int(math.ceil(max(abs(dg), abs(dt)) / step)))
        for s in range(1, n + 1):
            out.append(((a[0] + dg * s / n) % TAU, (a[1] + dt * s / n) % TAU))
    return out


def fold(poly):
    """Fold a T^2 polyline to the fundamental domain via P_point, splitting at
    genuine fold/wrap discontinuities. The input is densified first so that raw
    steps are small; any folded jump much larger than the raw step is a fold
    event. (An earlier coarse threshold silently dropped the interior strands.)"""
    pts = [P_point(p) for p in densify(poly)]
    pieces, cur = [], [pts[0]]
    for a, b in zip(pts, pts[1:]):
        if abs(b[0] - a[0]) > 0.3 or abs(b[1] - a[1]) > 0.3:
            if len(cur) > 1:
                pieces.append(cur)
            cur = [b]
        else:
            cur.append(b)
    if len(cur) > 1:
        pieces.append(cur)
    return pieces


def thin(piece, step=2):
    """Keep every step-th point (ends always kept) to limit TikZ path length."""
    if len(piece) <= 3:
        return piece
    out = piece[::step]
    if out[-1] != piece[-1]:
        out.append(piece[-1])
    return out


def tikz_path(piece, opts):
    coords = " -- ".join(f"({g:.4f},{t:.4f})" for (g, t) in piece)
    return f"\\draw[{opts}] {coords};"


def main():
    red, blue, _ = build_geometry()          # q=5 geometry, validated gate
    gens, d = bigon_matrix(red, blue)
    # red: BOTH lifts folded (C+ was simplified; rebuild full f8 for the pair)
    redfull = f8((2, 1), eps=0.10, phi=0.25)
    red_pieces = []
    for lift in redfull:
        red_pieces += fold(simplify(lift, 2e-4))
    blue_pieces = fold(blue)
    # the two support crossings (nearest self-crossings to the known coords)
    sx = self_intersections_detailed(blue)
    Ppts = [P_point(s['pt']) for s in sx]
    def nearest(target):
        return min(Ppts, key=lambda p: _tdist(p, target))
    sA = nearest((0.028, 1.272))
    sB = nearest((3.057, 4.981))

    lines = []
    lines.append("% AUTO-GENERATED by pillowcase/make_figure.py -- the REAL q=5 curves.")
    lines.append("%% blue folded into {} pieces; red (both lifts) into {} pieces.".format(
        len(blue_pieces), len(red_pieces)))
    lines.append("\\draw[thick] (0,0) rectangle (%.5f,%.5f);" % (PI, TAU))
    lines.append("\\foreach \\y in {0,%.5f,%.5f}{\\fill (-0.035,\\y-0.035) rectangle (0.035,\\y+0.035); \\fill (%.5f-0.035,\\y-0.035) rectangle (%.5f+0.035,\\y+0.035);}"
                 % (PI, TAU, PI, PI))
    lines.append("\\node[below] at (0,0) {\\footnotesize $(0,0)$};")
    lines.append("\\node[below] at (%.4f,0) {\\footnotesize $(\\pi,0)$};" % PI)
    lines.append("\\node[left] at (0,%.4f) {\\footnotesize $(0,2\\pi)$};" % TAU)
    lines.append("\\node[right] at (%.4f,%.4f) {\\footnotesize $(\\pi,2\\pi)$};" % (PI, TAU))
    lines.append("\\draw[->] (-0.15,0)--(%.4f,0) node[right] {\\footnotesize $\\gamma$};" % (PI + 0.35))
    lines.append("\\draw[->] (0,-0.15)--(0,%.4f) node[above] {\\footnotesize $\\theta$};" % (TAU + 0.4))
    # blue first and thicker; red thinner on top -- blue's interior strands run
    # nearly parallel to red (slopes 8/15 vs 1/2), so equal widths would hide one
    for p in blue_pieces:
        lines.append(tikz_path(thin(p, 2), "blue,line width=0.55pt"))
    for p in red_pieces:
        lines.append(tikz_path(thin(p, 1), "red,line width=0.45pt"))
    # generators (fold to P, dedupe)
    seen = []
    for g in gens:
        pp = P_point(g['pt'])
        if all(_tdist(pp, q) > 1e-3 for q in seen):
            seen.append(pp)
    for (g, t) in seen:
        lines.append("\\fill[black] (%.4f,%.4f) circle (1.4pt);" % (g, t))
    lines.append("\\draw[black,thick] (%.4f,%.4f) circle (3.2pt);" % sA)
    lines.append("\\draw[black,thick] (%.4f,%.4f) circle (3.2pt);" % sB)
    lines.append("\\node[right] at (%.4f,%.4f) {\\footnotesize $s_A$};" % (sA[0] + 0.08, sA[1]))
    lines.append("\\node[left] at (%.4f,%.4f) {\\footnotesize $s_B$};" % (sB[0] - 0.08, sB[1]))
    lines.append("\\node[blue] at (1.57,-0.55) {\\footnotesize blue $=\\Rp_t(Q_{1/3}+Q_{1/5})$};")
    lines.append("\\node[red] at (1.57,%.4f) {\\footnotesize red $=\\Rnat(\\Qh{-1/2})$};" % (TAU + 0.75))

    out = "\n".join(lines) + "\n"
    path = "../paper2/fig_q5.tex"
    with open(path, "w") as f:
        f.write(out)
    print(f"wrote {path}: {len(blue_pieces)} blue pieces, {len(red_pieces)} red pieces, "
          f"{len(seen)} generators, sA={tuple(round(v,3) for v in sA)}, sB={tuple(round(v,3) for v in sB)}")


if __name__ == "__main__":
    main()
