"""The perturbed traceless character variety of the torus-knot tangle of Hedden, Herald and Kirk, its image
L1 in the pillowcase, the earring curve L0, and the complex C(L0, L1): generators, bigons, gradings.

Floating-point numerics.  Notation and conventions are those of the paper:

  * pillowcase P = R^2/G, corners = images of the lattice (pi Z)^2, phi = theta - gamma;
  * Psi = (Psi_1, Psi_2) on the box [0,pi]^2 x [-1,1] in the coordinates (u, v, tau), eq. (3.1); the
    representation is A_1 -> exp(u Q_A), B_1 -> exp(v Q_B), Q_A = i, Q_B = tau i + sqrt(1 - tau^2) j, and the
    perturbation enters through A_2 -> exp(eps_A sin(u) Q_A), B_2 -> exp(eps_B sin(v) Q_B) [HHK18, (31)-(32)];
  * the restriction map Pi: a -> i, b -> exp(gamma k) i, c -> exp(theta k) i, gamma in [0, pi];
  * the earring L0, eq. (2.1), and its strands S^k_+ = L0~ + (0, 2 pi k), S^k_- = -L0~ + (0, 2 pi k);
  * generators x^+ (on the branch of L0 of slope < 1) and x^-; r_+ is the generator on the arc nearest the
    corner (0,0);
  * a bigon from p to q: counterclockwise boundary along L0 from p to q, then along L1 from q back to p;
  * relative grading by formula (2.2), with the Maslov index by the floor formula of Section 2.3, the triple
    index of [HHK18, Def. 2.5], and z computed from the word of the loop in pi_1(P*).

Only numpy is required.
"""
import math

import numpy as np

PI = math.pi
TAU = 2 * math.pi


# ============================================================================= knot data
def decomposition(n):
    """(r, s) of Theorem 1.1 for T(3, n): ((2n+1)/3, -2) if n = 1 (mod 3), ((n+1)/3, -1) if n = 2 (mod 3)."""
    r, s = ((2 * n + 1) // 3, -2) if n % 3 == 1 else ((n + 1) // 3, -1)
    assert 3 * r + n * s == 1
    return r, s


def signature(p, q):
    """signature of T(p,q), negative for positive torus knots (count of lattice points)."""
    sig = 0
    for i in range(1, p):
        for j in range(1, q):
            x = i * q + j * p                       # compare i/p + j/q with 1/2 and 3/2
            sig += -1 if (p * q < 2 * x < 3 * p * q) else 1
    return sig


def alexander_norm(p, q):
    """sum of |coefficients| of the Alexander polynomial of T(p,q) (via the semigroup generated by p, q)."""
    N = (p - 1) * (q - 1)
    S = set(a * p + b * q for a in range(N // p + 2) for b in range(N // q + 2))
    return sum(abs((k in S) - (k - 1 in S)) for k in range(N + 1))


def inat_degrees(p, q):
    """graded rank of I^natural(T(p,q); Q) in degrees 0..3 (degree = KM grading - sigma), formula (2.5)."""
    sig = abs(signature(p, q))
    N1, N3 = -(-sig // 4), sig // 4
    R = (1 + sig - alexander_norm(p, q)) // 2
    return (N3 + 1 - (R + 1) // 2, N1 - (R + 1) // 2, N1 - R // 2, N3 - R // 2)


# ============================================================================= quaternions (arrays (..., 4))
def qmul(p, q):
    w1, x1, y1, z1 = np.moveaxis(p, -1, 0)
    w2, x2, y2, z2 = np.moveaxis(q, -1, 0)
    return np.stack([w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2,
                     w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2,
                     w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2,
                     w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2], axis=-1)


def qconj(q):
    return q * np.array([1.0, -1.0, -1.0, -1.0])


def qexp(angle, axis):
    """exp(angle Q), Q the unit pure quaternion with vector part axis (arrays broadcast)."""
    angle = np.asarray(angle, float)
    return np.concatenate([np.cos(angle)[..., None], np.sin(angle)[..., None] * axis], axis=-1)


# ============================================================================= the tangle
class Tangle:
    """HHK's tangle for T(p,q) with p r + q s = 1 and holonomy perturbation parameters (eA, eB)."""

    def __init__(self, p, q, r, s, eA=0.0, eB=0.0):
        assert p * r + q * s == 1
        self.p, self.q, self.r, self.s, self.eA, self.eB = p, q, r, s, eA, eB

    def phases(self, u, v):
        p, q, r, s, eA, eB = self.p, self.q, self.r, self.s, self.eA, self.eB
        P1 = (s + p) * u + (q - r) * eA * np.sin(u)
        T1 = (q - r) * v - (s + p) * eB * np.sin(v)
        P2 = s * u - r * eA * np.sin(u)
        T2 = -r * v - s * eB * np.sin(v)
        return P1, T1, P2, T2

    def dphases(self, u, v):
        p, q, r, s, eA, eB = self.p, self.q, self.r, self.s, self.eA, self.eB
        return ((s + p) + (q - r) * eA * np.cos(u), (q - r) - (s + p) * eB * np.cos(v),
                s - r * eA * np.cos(u), -r - s * eB * np.cos(v))

    def psi(self, X):
        X = np.asarray(X, float)
        u, v, tau = X[..., 0], X[..., 1], X[..., 2]
        P1, T1, P2, T2 = self.phases(u, v)
        return np.stack([np.cos(P1) * np.cos(T1) - tau * np.sin(P1) * np.sin(T1),
                         np.cos(T2) * np.cos(P2) - tau * np.sin(T2) * np.sin(P2)], axis=-1)

    def jac(self, X):
        """d Psi / d(u, v, tau), shape (..., 2, 3)."""
        X = np.asarray(X, float)
        u, v, tau = X[..., 0], X[..., 1], X[..., 2]
        P1, T1, P2, T2 = self.phases(u, v)
        dP1, dT1, dP2, dT2 = self.dphases(u, v)
        c1, s1, c2, s2 = np.cos(P1), np.sin(P1), np.cos(T1), np.sin(T1)
        c3, s3, c4, s4 = np.cos(T2), np.sin(T2), np.cos(P2), np.sin(P2)
        r1 = np.stack([dP1 * (-s1 * c2 - tau * c1 * s2), dT1 * (-c1 * s2 - tau * s1 * c2), -s1 * s2], axis=-1)
        r2 = np.stack([dP2 * (-c3 * s4 - tau * s3 * c4), dT2 * (-s3 * c4 - tau * c3 * s4), -s3 * s4], axis=-1)
        return np.stack([r1, r2], axis=-2)

    def dpsi_deps(self, X):
        """d Psi / d(eps_A, eps_B) at X, shape (2, 2)."""
        u, v, tau = X
        p, q, r, s = self.p, self.q, self.r, self.s
        P1, T1, P2, T2 = self.phases(u, v)
        dPsi1_dP1 = -np.sin(P1) * np.cos(T1) - tau * np.cos(P1) * np.sin(T1)
        dPsi1_dT1 = -np.cos(P1) * np.sin(T1) - tau * np.sin(P1) * np.cos(T1)
        dPsi2_dP2 = -np.cos(T2) * np.sin(P2) - tau * np.sin(T2) * np.cos(P2)
        dPsi2_dT2 = -np.sin(T2) * np.cos(P2) - tau * np.cos(T2) * np.sin(P2)
        return np.array([[dPsi1_dP1 * (q - r) * math.sin(u), dPsi1_dT1 * (-(s + p)) * math.sin(v)],
                         [dPsi2_dP2 * (-r) * math.sin(u), dPsi2_dT2 * (-s) * math.sin(v)]])

    def boundary(self, X):
        """rho(a), rho(b), rho(c) as unit quaternions, from the words (31) of [HHK18]."""
        X = np.asarray(X, float)
        u, v, tau = X[..., 0], X[..., 1], np.clip(X[..., 2], -1.0, 1.0)
        QA = np.broadcast_to(np.array([1.0, 0.0, 0.0]), u.shape + (3,))
        QB = np.stack([tau, np.sqrt(np.maximum(0.0, 1 - tau * tau)), np.zeros_like(tau)], axis=-1)
        P1, T1, P2, T2 = self.phases(u, v)
        a = qmul(qexp(P1, QA), qexp(T1, QB))
        b = qmul(qexp(T2, QB), qexp(P2, QA))
        x = qexp(self.s * self.eB * np.sin(v) + self.r * v, QB)
        c = qmul(qmul(qconj(x), a), x)
        return a, b, c

    def pillow(self, X):
        """(gamma, theta) with gamma in [0, pi], theta in [0, 2 pi)."""
        a, b, c = self.boundary(X)
        av, bv, cv = a[..., 1:], b[..., 1:], c[..., 1:]
        cg = np.clip(np.sum(av * bv, -1), -1.0, 1.0)
        g = np.arccos(cg)
        sg = np.sin(g)
        e2 = (bv - cg[..., None] * av) / np.where(sg > 1e-9, sg, 1.0)[..., None]
        # on an edge (b = +-a) the frame is completed by c instead
        cp = cv - np.sum(cv * av, -1)[..., None] * av
        nc = np.linalg.norm(cp, axis=-1)
        e2 = np.where((sg > 1e-9)[..., None], e2, cp / np.where(nc > 1e-12, nc, 1.0)[..., None])
        th = np.mod(np.arctan2(np.sum(cv * e2, -1), np.sum(cv * av, -1)), TAU)
        return np.stack([g, th], axis=-1)

    def residuals(self, X):
        """max over X of |Psi| and of the deviation of a, b, c from being traceless."""
        a, b, c = self.boundary(X)
        return float(np.abs(self.psi(X)).max()), float(max(np.abs(a[..., 0]).max(), np.abs(b[..., 0]).max(),
                                                             np.abs(c[..., 0]).max()))


# ============================================================================= tracing W
def slice_points(T, nslice=900, ngrid=6000):
    """all solutions with |tau| < 1 on the slices u = const and v = const (vectorized bisection on
    F = C1 S2 - C2 S1, the resultant of Psi in tau)."""
    def CS(u, v):
        P1, T1, P2, T2 = T.phases(u, v)
        return np.cos(P1) * np.cos(T1), np.sin(P1) * np.sin(T1), np.cos(T2) * np.cos(P2), np.sin(T2) * np.sin(P2)

    def F(u, v):
        C1, S1, C2, S2 = CS(u, v)
        return C1 * S2 - C2 * S1

    out = []
    grid = np.linspace(1e-7, PI - 1e-7, ngrid)
    ws = np.linspace(PI / (2 * nslice), PI - PI / (2 * nslice), nslice)
    for axis in (0, 1):
        W, Z = np.meshgrid(ws, grid, indexing='ij')
        Fv = F(W, Z) if axis == 0 else F(Z, W)
        si, zi = np.nonzero(np.sign(Fv[:, :-1]) * np.sign(Fv[:, 1:]) < 0)
        lo, hi, w = grid[zi].copy(), grid[zi + 1].copy(), ws[si]
        flo = Fv[si, zi]
        for _ in range(55):
            mid = 0.5 * (lo + hi)
            fm = F(w, mid) if axis == 0 else F(mid, w)
            same = (fm > 0) == (flo > 0)
            lo = np.where(same, mid, lo); flo = np.where(same, fm, flo); hi = np.where(same, hi, mid)
        z = 0.5 * (lo + hi)
        u, v = (w, z) if axis == 0 else (z, w)
        C1, S1, C2, S2 = CS(u, v)
        tau = np.where(np.abs(S1) > np.abs(S2), C1 / np.where(S1 == 0, 1, S1), C2 / np.where(S2 == 0, 1, S2))
        X = np.c_[u, v, tau]
        ok = (np.abs(tau) < 1) & (np.abs(np.c_[C1 - S1 * tau, C2 - S2 * tau]).max(1) < 1e-8)
        out.append(X[ok])
    return np.vstack(out)


def _nullvec(J):
    _, sv, Vt = np.linalg.svd(J)
    return Vt[-1], sv


def _correct(T, X, tvec, it=8):
    for _ in range(it):
        g = T.psi(X)
        if np.abs(g).max() < 1e-12:
            return X, True
        M = np.vstack([T.jac(X), tvec])
        try:
            X = X + np.linalg.solve(M, np.r_[-g, 0.0])
        except np.linalg.LinAlgError:
            return X, False
    return X, np.abs(T.psi(X)).max() < 1e-10


def _inbox(X):
    return 0 <= X[0] <= PI and 0 <= X[1] <= PI and -1 <= X[2] <= 1


def trace_dir(T, X0, sgn, h0=2e-3, hmin=1e-10, maxlen=2e5, angtol=0.08):
    """pseudo-arclength continuation from X0 in the direction sgn * (null vector); stops on the boundary of the
    box or when the curve closes up.  Returns (points, status, smallest second singular value seen)."""
    pts = [X0.copy()]
    X = X0.copy()
    t, sv = _nullvec(T.jac(X)); t = sgn * t
    t0 = t.copy()
    h = h0
    minsv = sv[1]
    L = 0.0
    while L < maxlen:
        Xp = X + h * t
        Xn, ok = _correct(T, Xp, t)
        if ok:
            tn, svn = _nullvec(T.jac(Xn))
            if np.dot(tn, t) < 0:
                tn = -tn
            if math.acos(min(1.0, abs(np.dot(tn, t)))) > angtol or np.linalg.norm(Xn - Xp) > 0.3 * h:
                ok = False
        if not ok:
            h *= 0.5
            if h < hmin:
                return np.array(pts), 'stuck', minsv
            continue
        if not _inbox(Xn):
            lo, hi = 0.0, h
            for _ in range(60):
                mid = 0.5 * (lo + hi)
                Xm, okm = _correct(T, X + mid * t, t)
                if okm and _inbox(Xm):
                    lo = mid
                else:
                    hi = mid
            Xb, _ = _correct(T, X + lo * t, t)
            pts.append(np.clip(Xb, [0, 0, -1], [PI, PI, 1]))
            return np.array(pts), 'boundary', minsv
        minsv = min(minsv, svn[1])
        L += np.linalg.norm(Xn - X)
        X, t = Xn, tn
        pts.append(X.copy())
        if L > 20 * h0 and np.linalg.norm(X - X0) < 1.5 * h0 and np.dot(t, t0) > 0.9:
            pts.append(X0.copy())
            return np.array(pts), 'closed', minsv
        h = min(h0, h * 1.6)
    return np.array(pts), 'maxlen', minsv


class PointIndex:
    """uniform-grid index of points in R^3 for distance queries below a fixed radius."""

    def __init__(self, pts, cell):
        self.cell = cell
        self.pts = np.asarray(pts)
        keys = np.floor(self.pts / cell).astype(np.int64)
        order = np.lexsort(keys.T)
        self.pts, keys = self.pts[order], keys[order]
        self.buckets = {}
        if len(keys):
            brk = np.nonzero(np.any(np.diff(keys, axis=0) != 0, axis=1))[0] + 1
            for a, b in zip(np.r_[0, brk], np.r_[brk, len(keys)]):
                self.buckets[tuple(keys[a])] = (a, b)

    def near(self, X, radius):
        """distance from X to the nearest indexed point if it is below radius (else inf)."""
        k = np.floor(np.asarray(X) / self.cell).astype(np.int64)
        r = int(math.ceil(radius / self.cell))
        best = math.inf
        for dx in range(-r, r + 1):
            for dy in range(-r, r + 1):
                for dz in range(-r, r + 1):
                    ab = self.buckets.get((k[0] + dx, k[1] + dy, k[2] + dz))
                    if ab:
                        d = np.min(np.linalg.norm(self.pts[ab[0]:ab[1]] - X, axis=1))
                        best = min(best, d)
        return best if best < radius else math.inf


def _dense(pts, step):
    d = np.r_[0, np.cumsum(np.linalg.norm(np.diff(pts, axis=0), axis=1))]
    ss = np.r_[np.arange(0, d[-1], step), d[-1]]
    return np.c_[[np.interp(ss, d, pts[:, j]) for j in range(pts.shape[1])]].T


def trace_components(T, seeds, h0=2e-3, claim_tol=2e-2):
    """trace every component of W through the seeds: a seed within claim_tol of a traced component is not used
    again.  Returns a list of dicts (pts, kind in {'arc', 'circle', ...}, minsv)."""
    comps = []
    claimed = np.zeros(len(seeds), bool)
    seed_index = PointIndex(seeds, claim_tol)
    while not claimed.all():
        k = int(np.nonzero(~claimed)[0][0])
        X0 = seeds[k]
        f, st1, m1 = trace_dir(T, X0, +1, h0)
        if st1 == 'closed':
            pts, kind, msv = f, 'circle', m1
        else:
            b, st2, m2 = trace_dir(T, X0, -1, h0)
            pts = np.vstack([b[::-1], f[1:]])
            kind = 'arc' if st1 == st2 == 'boundary' else f'?{st1}/{st2}'
            msv = min(m1, m2)
        R = PointIndex(_dense(pts, claim_tol / 4), claim_tol)
        # claim the seeds within claim_tol of the traced polyline; only seeds in cells next to an occupied
        # cell need an exact test
        occ = set()
        for key in R.buckets:
            for dx in (-1, 0, 1):
                for dy in (-1, 0, 1):
                    for dz in (-1, 0, 1):
                        occ.add((key[0] + dx, key[1] + dy, key[2] + dz))
        keys = np.floor(seeds / claim_tol).astype(np.int64)
        for i in np.nonzero(~claimed)[0]:
            if tuple(keys[i]) in occ and R.near(seeds[i], claim_tol) < claim_tol:
                claimed[i] = True
        claimed[k] = True
        comps.append(dict(pts=pts, kind=kind, minsv=msv))
    return comps


def seed_coverage(seeds, comps, radius=1e-3):
    """largest distance from a seed to the traced set (capped at radius)."""
    R = PointIndex(np.vstack([_dense(c['pts'], radius / 4) for c in comps]), radius)
    return max(min(R.near(X, radius), radius) for X in seeds)


def project(T, X, it=10):
    """minimal-norm Newton projection of points X (N x 3) onto W."""
    X = np.array(X, float)
    for _ in range(it):
        G = T.psi(X)
        if np.abs(G).max() < 1e-13:
            break
        J = T.jac(X)
        Jt = np.swapaxes(J, -1, -2)
        X = X - (Jt @ np.linalg.solve(J @ Jt, G[..., None]))[..., 0]
        X[:, 2] = np.clip(X[:, 2], -1.0, 1.0)
    return X


def p_distance(P1, P2):
    """distance in the pillowcase metric (minimum over the action of G) of points given as (gamma, theta)."""
    best = None
    for sg in (1.0, -1.0):
        d = np.mod(sg * P2 - P1 + PI, TAU) - PI
        n = np.hypot(d[..., 0], d[..., 1])
        best = n if best is None else np.minimum(best, n)
    return best


def refine(T, pts, dimg, maxturn=0.15, maxpass=60):
    """insert points (projected onto W) until consecutive image points are at most dimg apart in P and the
    image polyline turns by at most maxturn (radians) at every vertex."""
    pts = np.asarray(pts, float)
    for _ in range(maxpass):
        P = T.pillow(pts)
        d = p_distance(P[:-1], P[1:])
        m = np.where(d > dimg, np.ceil(d / dimg), 1).astype(int)
        L = lift(P)
        v = np.diff(L, axis=0)
        ang = np.arctan2(v[:, 1], v[:, 0])
        turn = np.abs(np.mod(np.diff(ang) + PI, TAU) - PI)
        sharp = np.nonzero((turn > maxturn) & (d[:-1] > 1e-9) & (d[1:] > 1e-9))[0]
        m[sharp] = np.maximum(m[sharp], 2)
        m[sharp + 1] = np.maximum(m[sharp + 1], 2)
        m = np.minimum(m, 400)
        bad = np.nonzero(m > 1)[0]
        if len(bad) == 0:
            break
        new, where = [], []
        for i in bad:
            s = np.arange(1, m[i])[:, None] / m[i]
            new.append(pts[i] + s * (pts[i + 1] - pts[i]))
            where.append(np.full(m[i] - 1, i + 1))
        new = project(T, np.vstack(new))
        pts = np.insert(pts, np.concatenate(where), new, axis=0)
    return pts


def trace_variety(T, nslice=900, ngrid=6000, h0=2e-3, dimg=3e-3):
    seeds = slice_points(T, nslice, ngrid)
    comps = trace_components(T, seeds, h0)
    for c in comps:
        c['pts'] = refine(T, c['pts'], dimg)
        c['L'] = lift(T.pillow(c['pts']))
    return comps, seeds


# ============================================================================= lifts to R^2
def lift(P):
    """continuous lift to R^2 of a sequence of pillowcase points (gamma, theta)."""
    P = np.asarray(P, float)
    out = np.empty_like(P)
    out[0] = P[0]
    g, t = P[:, 0].tolist(), P[:, 1].tolist()
    pg, pt = g[0], t[0]
    for i in range(1, len(P)):
        best = None
        for sg in (1.0, -1.0):
            G0, T0 = sg * g[i], sg * t[i]
            cg = G0 + TAU * round((pg - G0) / TAU)
            ct = T0 + TAU * round((pt - T0) / TAU)
            d = (cg - pg) ** 2 + (ct - pt) ** 2
            if best is None or d < best[0]:
                best = (d, cg, ct)
        pg, pt = best[1], best[2]
        out[i] = (pg, pt)
    return out


def arc_lift(L):
    """the lift of the arc that starts at the lattice point (0,0), at an end mapping to the corner (0,0), and
    enters {gamma > 0}; endpoints snapped to the lattice."""
    L = np.array(L)
    c0 = np.round(L[0] / PI).astype(int)
    if not (c0[0] % 2 == 0 and c0[1] % 2 == 0):
        L = L[::-1].copy()
        c0 = np.round(L[0] / PI).astype(int)
    L = L - c0 * PI
    if L[min(40, len(L) - 1), 0] < 0:
        L = -L
    L[0] = 0.0
    L[-1] = np.round(L[-1] / PI) * PI
    return L


def circle_lift(L, periods):
    """lift of a circle over the given number of periods (L is one period, closed in P); returns the
    multi-period polyline and the displacement per period."""
    Lc = L[:-1]
    disp = L[-1] - L[0]
    lo = -(periods // 2)
    M = np.vstack([Lc + j * disp for j in range(lo, lo + periods)] + [Lc[:1] + (lo + periods) * disp])
    return M, disp


# ============================================================================= the earring
def strand(sign, k, eps, t):
    t = np.asarray(t, float)
    P = np.stack([t + eps * np.sin(t) + PI / 2, t - eps * np.sin(t) + PI / 2], axis=-1)
    if sign < 0:
        P = -P
    return P + np.array([0.0, TAU * k])


def strand_theta(sign, k, eps, gam):
    """theta of the strand S^k_sign above gamma (strands are graphs over gamma) and its parameter t."""
    target = np.asarray(gam, float) - PI / 2 if sign > 0 else -np.asarray(gam, float) - PI / 2
    t = np.array(target, dtype=float)
    for _ in range(50):
        t = t - (t + eps * np.sin(t) - target) / (1 + eps * np.cos(t))
    th = t - eps * np.sin(t) + PI / 2
    return (th if sign > 0 else -th) + TAU * k, t


def L0_line_angle(t, eps):
    """angle in [0, pi) of the tangent line of L0 at parameter t (the same for both strand families)."""
    return math.atan2(1 - eps * math.cos(t), 1 + eps * math.cos(t))


def strand_path(sign, k, eps, g0, g1, n=3000):
    gs = np.linspace(g0, g1, n)
    return np.c_[gs, strand_theta(sign, k, eps, gs)[0]]


def generators(L, eps):
    """transverse intersections of the polyline L (in R^2) with all strands, in the order along L."""
    out = []
    for sign in (1, -1):
        th, _ = strand_theta(sign, 0, eps, L[:, 0])
        off = L[:, 1] - th                                       # = 2 pi k exactly on S^k_sign
        kk = np.floor(off / TAU)
        for i in np.nonzero(kk[:-1] != kk[1:])[0]:
            lo_, hi_ = sorted((off[i], off[i + 1]))
            for k in range(math.ceil(lo_ / TAU), math.floor(hi_ / TAU) + 1):
                if not (lo_ < TAU * k < hi_):
                    continue
                a, b, fa = 0.0, 1.0, off[i] - TAU * k
                for _ in range(60):
                    m = 0.5 * (a + b)
                    Pm = L[i] + m * (L[i + 1] - L[i])
                    fm = Pm[1] - strand_theta(sign, 0, eps, Pm[0])[0] - TAU * k
                    if (fm > 0) == (fa > 0):
                        a, fa = m, fm
                    else:
                        b = m
                m = 0.5 * (a + b)
                Pm = L[i] + m * (L[i + 1] - L[i])
                _, tpar = strand_theta(sign, 0, eps, Pm[0])
                slope = (1 - eps * math.cos(tpar)) / (1 + eps * math.cos(tpar))
                out.append(dict(i=int(i), pos=float(i + m), pt=Pm, sign=sign, k=k, t=float(tpar),
                                label='x+' if slope < 1 else 'x-'))
    out.sort(key=lambda d: d['pos'])
    return out


# ============================================================================= polylines and topology
def resample(L, step):
    return _dense(np.asarray(L, float), step)


def polyline_between(L, pos0, pos1):
    """sub-polyline of L between fractional positions pos0 -> pos1 (either order)."""
    def pt(pos):
        i = min(int(math.floor(pos)), len(L) - 2)
        return L[i] + (pos - i) * (L[i + 1] - L[i])
    if pos0 <= pos1:
        mid = L[int(math.floor(pos0)) + 1:int(math.floor(pos1)) + 1]
    else:
        mid = L[int(math.floor(pos1)) + 1:int(math.floor(pos0)) + 1][::-1]
    return np.vstack([pt(pos0), mid, pt(pos1)])


def signed_area(loop):
    x, y = loop[:, 0], loop[:, 1]
    return 0.5 * float(np.sum(x * np.roll(y, -1) - np.roll(x, -1) * y))


def lattice_windings(loop, pad=1):
    """nonzero winding numbers of the closed polyline about the lattice points (keys in units of pi)."""
    loop = np.vstack([loop, loop[:1]])
    lo_ = np.floor(loop.min(0) / PI).astype(int) - pad
    hi_ = np.ceil(loop.max(0) / PI).astype(int) + pad
    out = {}
    for i in range(lo_[0], hi_[0] + 1):
        d = loop - np.array([i * PI, 0.0])
        for j in range(lo_[1], hi_[1] + 1):
            e = d - np.array([0.0, j * PI])
            a = np.arctan2(e[:, 1], e[:, 0])
            w = np.sum(np.mod(np.diff(a) + PI, TAU) - PI) / TAU
            if abs(w) > 1e-3:
                out[(i, j)] = int(round(w))
    return out


def reduce_word(w):
    out = []
    for g in w:
        if out and out[-1][0] == g[0] and out[-1][1] == -g[1]:
            out.pop()
        else:
            out.append(g)
    return out


def cyclic_reduce(w):
    w = reduce_word(w)
    while len(w) >= 2 and w[0][0] == w[-1][0] and w[0][1] == -w[-1][1]:
        w = w[1:-1]
    return w


def gap_word(path, merged=()):
    """class of a path in R^2 minus the lattice: the reduced sequence of gaps it crosses on the vertical lines
    gamma = I pi (gap (I, J) is the segment from (I pi, J pi) to (I pi, (J+1) pi)).  `merged` lists lattice points
    that are not removed (ends of an arc); the two gaps next to such a point count as one."""
    P = np.asarray(path)
    mg = {(I, J): (I, J - 1) for (I, J) in merged}
    w = []
    for a, b in zip(P[:-1], P[1:]):
        xa, xb = a[0] / PI, b[0] / PI
        fa, fb = math.floor(xa), math.floor(xb)
        if fa == fb:
            continue
        step = 1 if xb > xa else -1
        for I in (range(fa + 1, fb + 1) if step > 0 else range(fa, fb, -1)):
            s = (I - xa) / (xb - xa)
            y = (a[1] + s * (b[1] - a[1])) / PI
            J = math.floor(y)
            w.append((mg.get((I, J), (I, J)), step))
    return reduce_word(w)


def tree_word(path):
    """word in pi_1(P*) = F(X, Y, Z) of a path in R^2 minus the lattice (base point in the open front face), read
    from its crossings with the preimage of the tree formed by the left edge (letter X), the bottom edge
    theta = 0 (Y) and the right edge (Z)."""
    w = []
    P = np.asarray(path)
    for a, b in zip(P[:-1], P[1:]):
        ev = []
        ga, gb = a[0] / PI, b[0] / PI
        if math.floor(ga) != math.floor(gb):
            step = 1 if gb > ga else -1
            for m in (range(math.floor(ga) + 1, math.floor(gb) + 1) if step > 0 else range(math.floor(ga), math.floor(gb), -1)):
                s = (m - ga) / (gb - ga)
                up = ((a[1] + s * (b[1] - a[1])) % TAU) < PI
                ev.append((s, 'X' if m % 2 == 0 else 'Z', step * (1 if up else -1)))
        ta, tb = a[1] / TAU, b[1] / TAU
        if math.floor(ta) != math.floor(tb):
            step = 1 if tb > ta else -1
            for n in (range(math.floor(ta) + 1, math.floor(tb) + 1) if step > 0 else range(math.floor(ta), math.floor(tb), -1)):
                s = (n - ta) / (tb - ta)
                right = ((a[0] + s * (b[0] - a[0])) % TAU) < PI
                ev.append((s, 'Y', -step * (1 if right else -1)))
        ev.sort()
        w.extend((L, e) for _, L, e in ev)
    return reduce_word(w)


Z_OF_LETTER = {'X': 1, 'Y': 2, 'Z': 1}


def z_class(path):
    """z in Z/4 of a loop in P*: 1 on a small counterclockwise loop about a corner (Section 2.3)."""
    w = tree_word(path)
    return sum(Z_OF_LETTER[L] * e for L, e in w) % 4, w


def word_str(w):
    return ''.join(L if e > 0 else L.lower() for L, e in w)


def corner_loops_z():
    """z of small counterclockwise loops about the four corners (all should be 1)."""
    out = {}
    for name, c in (('(0,0)', (0, 0)), ('(pi,pi)', (PI, PI)), ('(pi,0)', (PI, 0)), ('(0,pi)', (0, PI))):
        ph = np.linspace(-PI / 2 + 0.3, PI / 2 + 0.3, 400)          # half a turn in R^2 = one turn in P
        out[name] = z_class(np.c_[c[0] + 0.2 * np.cos(ph), c[1] + 0.2 * np.sin(ph)])[0]
    return out


def seg_crossings(P, Q=None, cell=0.05, skip_adjacent=2):
    """proper crossings between segments of the polylines P and Q (or of P with itself)."""
    self_ = Q is None
    Q = P if self_ else Q
    P, Q = np.asarray(P), np.asarray(Q)
    grid = {}
    for j in range(len(Q) - 1):
        a, b = Q[j], Q[j + 1]
        for cx in range(int(math.floor(min(a[0], b[0]) / cell)), int(math.floor(max(a[0], b[0]) / cell)) + 1):
            for cy in range(int(math.floor(min(a[1], b[1]) / cell)), int(math.floor(max(a[1], b[1]) / cell)) + 1):
                grid.setdefault((cx, cy), []).append(j)
    seen, res = set(), []
    for i in range(len(P) - 1):
        a, b = P[i], P[i + 1]
        cand = set()
        for cx in range(int(math.floor(min(a[0], b[0]) / cell)), int(math.floor(max(a[0], b[0]) / cell)) + 1):
            for cy in range(int(math.floor(min(a[1], b[1]) / cell)), int(math.floor(max(a[1], b[1]) / cell)) + 1):
                cand.update(grid.get((cx, cy), ()))
        for j in cand:
            if self_ and (j < i or j <= i + skip_adjacent):
                continue
            c, d = Q[j], Q[j + 1]
            r_, s_ = b - a, d - c
            den = r_[0] * s_[1] - r_[1] * s_[0]
            if den == 0:
                continue
            qp = c - a
            t = (qp[0] * s_[1] - qp[1] * s_[0]) / den
            u = (qp[0] * r_[1] - qp[1] * r_[0]) / den
            if 0 <= t < 1 and 0 <= u < 1 and (i, j) not in seen:
                seen.add((i, j))
                res.append((i, j, t, u, a + t * r_))
    return res


def direction_changes(f, trim=5):
    """number of sign changes of the increments of f (ignoring zero increments and `trim` points at each end)."""
    d = np.diff(np.asarray(f)[trim:len(f) - trim])
    s = np.sign(d[d != 0])
    return int(np.sum(s[1:] != s[:-1]))


def tangent_passages(L, trim=5):
    """number of times the tangent line of the polyline passes the line field of slope one (angle pi/4 mod pi)."""
    d = np.diff(np.asarray(L)[trim:len(L) - trim], axis=0)
    d = d[np.linalg.norm(d, axis=1) > 0]
    ang = np.unwrap(2 * np.arctan2(d[:, 1], d[:, 0])) / 2
    k = np.floor((ang - PI / 4 - 1e-9) / PI)
    return int(np.sum(np.abs(np.diff(k))))


# ============================================================================= grading formula (2.2)
def _line_angle(v):
    return math.atan2(v[1], v[0]) % PI


def _mu(angles, delta=1e-9):
    a = np.unwrap(2 * np.asarray(angles)) / 2
    f = lambda x: math.floor((x - PI / 4 - delta) / PI)
    return f(a[-1]) - f(a[0])


def _tau3(a0, a1, a=PI / 4):
    """triple index: 1 iff the clockwise rotation from the line of angle a0 to that of angle a1 passes a."""
    t = (a0 - a1) % PI
    d = (a0 - a) % PI
    return 1 if 0 < d < t else 0


def grading(L, p, q, eps, forward=True, alpha1=None):
    """gr(p, q) in Z/4 by (2.2): alpha_0 along L0 from p to q (forward or backward in the parameter of L0),
    alpha_1 along L1 from q to p (by default the sub-path of the polyline L between them)."""
    tp, tq = p['t'], q['t']
    m = (math.floor((tp - tq) / TAU) + 1) if forward else (math.ceil((tp - tq) / TAU) - 1)
    ts = np.linspace(tp, tq + TAU * m, 3000)
    a0 = strand(p['sign'], p['k'], eps, ts)
    mu0 = _mu([L0_line_angle(t, eps) for t in ts])

    def h(P):                       # the deck transformation taking the lift of q to the end of alpha_0
        P = np.asarray(P, float)
        return (p['sign'] * q['sign'] * (P - np.array([0.0, TAU * q['k']])) + p['sign'] * TAU * m * np.array([1.0, 1.0])
                + np.array([0.0, TAU * p['k']]))
    assert np.allclose(h(q['pt']), a0[-1], atol=1e-6)
    a1 = alpha1 if alpha1 is not None else polyline_between(L, q['pos'], p['pos'])
    a1h = np.array([h(P) for P in a1])
    ang1 = [_line_angle(a1[k + 1] - a1[k]) for k in range(len(a1) - 1) if np.linalg.norm(a1[k + 1] - a1[k]) > 1e-12]
    mu1 = _mu(ang1)
    line_L1 = lambda g: _line_angle(L[g['i'] + 1] - L[g['i']])
    tp_ = _tau3(L0_line_angle(tp, eps), line_L1(p))
    tq_ = _tau3(L0_line_angle(tq, eps), line_L1(q))
    z, _ = z_class(np.vstack([a0, a1h[1:]]))
    return (mu0 + mu1 + tp_ - tq_ + z) % 4


def grading_both(L, p, q, eps):
    """gr(p, q) with alpha_0 taken in both directions along L0; returns (value, directions agree)."""
    a, b = grading(L, p, q, eps, True), grading(L, p, q, eps, False)
    return a, a == b


# ============================================================================= bigons
def bigon_candidates(L, gens, eps, sources=None):
    """for each ordered pair (p, q) of generators on the same strand, the closed curve formed by the strand from
    p to q and the sub-path of L from q to p (Lemma 6.4).  It bounds a bigon from p to q exactly when it is
    null-homotopic in R^2 minus the lattice and is the counterclockwise boundary of an immersed disc with convex
    corners; here: trivial windings and gap word, positive signed area, and no self-crossings."""
    out = []
    for p in (sources if sources is not None else gens):
        for q in gens:
            if q is p or p['sign'] != q['sign'] or p['k'] != q['k']:
                continue
            a0 = strand_path(p['sign'], p['k'], eps, p['pt'][0], q['pt'][0])
            a1 = polyline_between(L, q['pos'], p['pos'])
            loop = np.vstack([a0, a1[1:]])
            W = lattice_windings(loop[:-1])
            gw = gap_word(np.vstack([loop, loop[:1]]))
            area = signed_area(loop)
            simple = None
            if not W and not gw:
                simple = len(seg_crossings(resample(np.vstack([loop, loop[:1]]), min(0.2 * eps, 0.002)),
                                           cell=0.02, skip_adjacent=2)) == 0
            out.append(dict(p=p, q=q, windings=W, word_len=len(gw), area=area, simple=simple,
                            bigon=(not W and not gw and area > 0 and simple)))
    return out


def rank_f2(M):
    M = np.array(M, dtype=np.int64) % 2
    r = 0
    for c in range(M.shape[1]):
        piv = next((k for k in range(r, M.shape[0]) if M[k, c]), None)
        if piv is None:
            continue
        M[[r, piv]] = M[[piv, r]]
        for k in range(M.shape[0]):
            if k != r and M[k, c]:
                M[k] ^= M[r]
        r += 1
    return r


# ============================================================================= the complex of a traced variety
def analyse_complex(comps, eps, sigma, gradings=True, periods=5):
    """generators, bigons, gradings (absolute on the arc via gr(r_+) = sigma, relative on circles) and
    homology of C(L0, L1) for the traced components.  Returns a dict."""
    # 'odd' collects null-homotopic counterclockwise candidate loops that are not simple (none occur here)
    res = dict(arc=None, circles=[], ngen=0, nbigon=0, rank_d=0, odd=[])
    for c in comps:
        if c['kind'] == 'arc':
            L = arc_lift(c['L'])
            G = generators(L, eps)
            ir = min(range(len(G)), key=lambda j: np.hypot(*G[j]['pt'])) if G else None
            for j, g in enumerate(G):
                g['rplus'] = (j == ir)
            cands = bigon_candidates(L, G, eps)
            bigons = [(G.index(b['p']), G.index(b['q'])) for b in cands if b['bigon']]
            res['odd'] += [b for b in cands if b['simple'] is False and b['area'] > 0]
            A = dict(L=L, gens=G, bigons=bigons, cands=cands, end=tuple(int(v) for v in np.round(L[-1] / PI)))
            if gradings and G:
                gr, agree = [], True
                for j, g in enumerate(G):
                    if j == ir:
                        gr.append(sigma % 4)
                        continue
                    v, ok = grading_both(L, g, G[ir], eps)
                    agree &= ok
                    gr.append((sigma + v) % 4)
                A['gr'], A['agree'] = gr, agree
                # gr(x^+, x^-) = 1 for the two generators over each crossing with a line Delta_k
                pairs = []
                for a, b in zip(G[:-1], G[1:]):
                    if a.get('rplus') or b.get('rplus') or a['label'] == b['label']:
                        continue
                    if abs((a['pt'][1] - a['pt'][0]) - (b['pt'][1] - b['pt'][0])) < 6 * eps:
                        xp, xm = (a, b) if a['label'] == 'x+' else (b, a)
                        pairs.append(grading_both(L, xp, xm, eps)[0])
                A['pair_gr'] = pairs
            d = np.zeros((len(G), len(G)), int)
            for i, j in bigons:
                d[j, i] ^= 1
            A['rank_d'] = rank_f2(d)
            res['arc'] = A
            res['ngen'] += len(G); res['nbigon'] += len(bigons); res['rank_d'] += A['rank_d']
        elif c['kind'] == 'circle':
            M, disp = circle_lift(c['L'], periods)
            G = generators(M, eps)
            lo_, hi_ = len(M) * (periods // 2) / periods, len(M) * (periods // 2 + 1) / periods
            Gm = [g for g in G if lo_ <= g['pos'] < hi_]
            cands = bigon_candidates(M, G, eps, sources=Gm)
            bigons = [b for b in cands if b['bigon']]
            res['odd'] += [b for b in cands if b['simple'] is False and b['area'] > 0]
            C = dict(disp=disp, gens=Gm, ncand=len(cands), nbigon=len(bigons), M=M, allgens=G)
            if gradings and Gm:
                base = Gm[0]
                rel, agree = [], True
                per = len(M) / periods
                for g in Gm:
                    if g is base:
                        rel.append(0)
                        continue
                    vals = set()
                    for shift in (0, -1, 1):     # the generator in this period, and its copies one period away
                        cand = [h for h in G if abs(h['pos'] - (g['pos'] + shift * per)) < 3 and h['sign'] == g['sign']]
                        for h in cand:
                            vals.update(grading_both(M, h, base, eps)[:1])
                    agree &= len(vals) == 1
                    rel.append(min(vals))
                C['rel'], C['agree'] = rel, agree
            res['circles'].append(C)
            res['ngen'] += len(Gm); res['nbigon'] += len(bigons)
    return res


def circle_degree_pattern(C):
    """for a circle with four generators: (one generator in each relative grading, the two x^- differ by 2,
    each x^+ is one above an x^-)."""
    rel, labels = C['rel'], [g['label'] for g in C['gens']]
    xm = [r for r, l in zip(rel, labels) if l == 'x-']
    xp = [r for r, l in zip(rel, labels) if l == 'x+']
    return (len(rel) == 4 and sorted(rel) == [0, 1, 2, 3] and len(xm) == 2 and (xm[0] - xm[1]) % 4 == 2
            and sorted((x + 1) % 4 for x in xm) == sorted(xp))
