"""Encoding curves in the pillowcase as twisted complexes over the two-arc algebra (Section 6.3 and Appendix A.3).

The planar cover.  The punctured pillowcase is (R^2 - Z^2)/G, with G generated by the translations (x, y) ->
(x + 2, y), (x, y) -> (x, y + 2) and the reflection v -> -v.  Smith's coordinates (gamma, theta) correspond to
    x = 1 - theta/pi,   y = 1 + gamma/pi,
so that the lattice classes mod 2 are the corners
    (odd, odd)   = (0, 0)       ('R' in the tables below)
    (odd, even)  = (pi, 0)      ('M')
    (even, even) = (pi, pi)     ('L')
    (even, odd)  = (0, pi)      ('*', sent to infinity: the chart of Section 6.3).
The two arcs of the arc system lift to the grid segments joining adjacent points of class (even, odd): vertical
segments in {x in 2Z} and horizontal segments in {y in 2Z + 1}.  A transverse crossing of a segment contributes two
generators joined by D (iota_circ on vertical segments, iota_bullet on horizontal ones), oriented along the
direction of travel iff the midpoint of the segment lies to the left; a passage through a cell between two
crossings contributes S^|k|, where k is the signed number of rays from the cell centre to its corners that the
path crosses.  Arc ends at corners of class (0, 0) or (pi, pi) contribute one generator, ends at (pi, 0) none.
Identity entries are cancelled at the end.  The conventions were compared with the invariants of 216 rational
tangles computed by Zibrowius's program kht++ (kwz_encoder_check.py).

The translation Phi(gamma, theta) = (gamma + pi, theta) of Section 7.1 is (x, y) -> (x, y + 1).

All coordinates are exact rationals (fractions.Fraction).
"""
from fractions import Fraction as F
import math

from kwz_algebra import mul, check_obj

VERT_IDEM = 'w'
EPS = F(1, 997)                    # displacement of lines from the lattice points they pass
PHI = (0, 1)                       # the translation Phi in planar coordinates
NAME = {'P2': 'R', 'P3': 'M', 'P1': 'L', 'STAR': '*'}
CORNER = {'R': '(0,0)', 'M': '(pi,0)', 'L': '(pi,pi)', '*': '(0,pi)'}


def cls(P):
    x, y = P
    return {(0, 1): 'STAR', (0, 0): 'P1', (1, 1): 'P2', (1, 0): 'P3'}[(x % 2, y % 2)]


def corner_of(P):
    return CORNER[NAME[cls(P)]]


def _is_lattice(p):
    return p[0].denominator == 1 and p[1].denominator == 1


def _floor(x):
    return x.numerator // x.denominator


def _cell_of(p):
    a = _floor(p[0] / 2) * 2
    b = _floor((p[1] + 1) / 2) * 2
    return (a + 1, b)


def _crossings(p, q):
    """Grid crossings of the half-open segment (p, q]: list of (t, 'V' or 'H', point)."""
    out = []
    (x0, y0), (x1, y1) = p, q
    if x1 != x0:
        lo, hi = min(x0, x1), max(x0, x1)
        X = _floor(lo / 2) * 2
        while X <= hi:
            t = (X - x0) / (x1 - x0)
            if 0 < t <= 1:
                out.append((t, 'V', (F(X), y0 + t * (y1 - y0))))
            X += 2
    if y1 != y0:
        lo, hi = min(y0, y1), max(y0, y1)
        Y = _floor((lo - 1) / 2) * 2 + 1
        while Y <= hi:
            t = (Y - y0) / (y1 - y0)
            if 0 < t <= 1:
                out.append((t, 'H', (x0 + t * (x1 - x0), F(Y))))
            Y += 2
    out.sort(key=lambda e: e[0])
    for i in range(len(out) - 1):
        assert out[i][0] != out[i + 1][0], ('passes through a grid vertex', p, q)
    return out


def _midpoint(kind, pt):
    if kind == 'V':
        return (pt[0], F(_floor((pt[1] + 1) / 2) * 2))
    return (F(_floor(pt[0] / 2) * 2 + 1), pt[1])


def _det(u, v):
    return u[0] * v[1] - u[1] * v[0]


def _ray_count(c, path):
    """Signed number of crossings of the four rays from the cell centre c towards its corners by the polyline path
    (anticlockwise positive)."""
    k = 0
    for a, b in zip(path, path[1:]):
        for d in ((1, 1), (-1, 1), (-1, -1), (1, -1)):
            v = (b[0] - a[0], b[1] - a[1])
            den = _det(v, d)
            if den == 0:
                continue
            w = (c[0] - a[0], c[1] - a[1])
            s = _det(w, d) / den
            u = _det(w, v) / den
            if 0 < s <= 1 and u > 0:
                k += 1 if _det((a[0] - c[0], a[1] - c[1]), v) > 0 else -1
    return k


def encode(pts, closed=False):
    """Encode a polyline in the plane.  Arc: pts[0] and pts[-1] are lattice points of class other than (0, pi), and
    the interior avoids the lattice.  Closed curve: pts[-1] = pts[0] + (deck translation), pts[0] in an open cell."""
    pts = [(F(x), F(y)) for x, y in pts]
    for p in (pts[1:-1] if not closed else pts):
        assert not _is_lattice(p), ('vertex on the lattice', p)
    ev = []
    nseg = len(pts) - 1
    for i in range(nseg):
        p, q = pts[i], pts[i + 1]
        v = (q[0] - p[0], q[1] - p[1])
        for t, kind, pt in _crossings(p, q):
            if not closed and i == nseg - 1 and t == 1:
                continue
            assert not _is_lattice(pt), ('passes through a puncture', pt)
            ev.append((i, t, kind, pt, v))
    T = None
    if closed:
        T = (pts[-1][0] - pts[0][0], pts[-1][1] - pts[0][1])
        assert T[0] % 2 == 0 and T[1] % 2 == 0
        p0 = pts[0]
        assert not (p0[0].denominator == 1 and p0[0].numerator % 2 == 0), ('closed curve starts on a grid line', p0)
        assert not (p0[1].denominator == 1 and p0[1].numerator % 2 == 1), ('closed curve starts on a grid line', p0)

    def pathpts(e0, e1, wrap=False):
        i0, t0, _, p0, _ = e0
        i1, t1, _, p1, _ = e1
        seq = [p0]
        if wrap:
            seq += pts[i0 + 1:]
            seq += [(x + T[0], y + T[1]) for (x, y) in pts[1:i1 + 1]]
            seq.append((p1[0] + T[0], p1[1] + T[1]))
        else:
            seq += pts[i0 + 1:i1 + 1]
            seq.append(p1)
        return seq

    def idem(kind):
        return VERT_IDEM if kind == 'V' else ('b' if VERT_IDEM == 'w' else 'w')

    def d_dir(kind, pt, v):
        m = _midpoint(kind, pt)
        s = _det(v, (m[0] - pt[0], m[1] - pt[1]))
        assert s != 0
        return 1 if s > 0 else -1

    if not closed:
        P0 = pts[0]
        assert _is_lattice(P0) and cls((int(P0[0]), int(P0[1]))) != 'STAR'
        c0 = cls((int(P0[0]), int(P0[1])))
        v0 = (pts[1][0] - P0[0], pts[1][1] - P0[1])
        if c0 in ('P1', 'P2'):
            ev.insert(0, (0, F(0), 'V' if c0 == 'P1' else 'H', P0, v0, 'half_out'))
    evs = [e if len(e) == 6 else e + ('full',) for e in ev]
    if not closed:
        P1 = pts[-1]
        assert _is_lattice(P1) and cls((int(P1[0]), int(P1[1]))) != 'STAR'
        c1 = cls((int(P1[0]), int(P1[1])))
        v1 = (P1[0] - pts[-2][0], P1[1] - pts[-2][1])
        if c1 in ('P1', 'P2'):
            evs.append((nseg - 1, F(1), 'V' if c1 == 'P1' else 'H', P1, v1, 'half_in'))
    items = []
    n = len(evs)
    for j, e in enumerate(evs):
        i, t, kind, pt, v, typ = e
        if typ == 'full':
            items += [('g', idem(kind)), ('a', 'D', 1, d_dir(kind, pt, v)), ('g', idem(kind))]
        else:
            items.append(('g', idem(kind)))
        if j < n - 1 or closed:
            e1 = evs[(j + 1) % n]
            wrap = closed and j == n - 1
            path = pathpts(e[:5], e1[:5], wrap)
            tiny = F(1, 10 ** 9)
            c = _cell_of((pt[0] + tiny * v[0], pt[1] + tiny * v[1]))
            k = _ray_count(c, path)
            items.append(('a', 'S', abs(k), (1 if k > 0 else -1) if k != 0 else 0))
    gens = [it[1] for it in items if it[0] == 'g']
    arrs = [it for it in items if it[0] == 'a']
    m = len(gens)
    assert len(arrs) == (m if closed else m - 1)
    arrows, ident = [], []
    for j, (_, kind, k, dr) in enumerate(arrs):
        a, b = j, (j + 1) % m
        if k == 0:
            ident.append((a, b))
            continue
        arrows.append((a, kind, k, b) if dr > 0 else (b, kind, k, a))
    return check_obj(_cancel_identities(gens, arrows, ident))


def _cancel_identities(gens, arrows, ident):
    """Gaussian elimination of the identity entries x -1- y (a unit in either direction)."""
    gens = list(gens)
    arrows = list(arrows)
    alive = set(range(len(gens)))
    for (x, y) in ident:
        ins_y = [(u, kd, k) for (u, kd, k, w) in arrows if w == y and u != x]
        outs_x = [(kd, k, v) for (u, kd, k, v) in arrows if u == x and v != y]
        ins_x = [(u, kd, k) for (u, kd, k, w) in arrows if w == x]
        outs_y = [(kd, k, v) for (u, kd, k, v) in arrows if u == y]
        new = [t for t in arrows if t[0] not in (x, y) and t[3] not in (x, y)]
        for (u, kd1, k1) in ins_y:
            for (kd2, k2, v) in outs_x:
                p = mul((kd1, k1), (kd2, k2))
                if p is not None:
                    new.append((u, p[0], p[1], v))
        if not ins_y and not outs_x:
            for (u, kd1, k1) in ins_x:
                for (kd2, k2, v) in outs_y:
                    p = mul((kd1, k1), (kd2, k2))
                    if p is not None:
                        new.append((u, p[0], p[1], v))
        arrows = new
        alive -= {x, y}
    keep = sorted(alive)
    mp = {v: t for t, v in enumerate(keep)}
    cnt = {}
    for (u, kd, k, v) in arrows:
        key = (mp[u], kd, k, mp[v])
        cnt[key] = cnt.get(key, 0) ^ 1
    return ([gens[v] for v in keep], [key for key, c in cnt.items() if c])


# ----------------------------------------------------------------------------------------------- linear curves

def shift(pts, v=PHI):
    return [(F(x) + v[0], F(y) + v[1]) for (x, y) in pts]


def offset(P, w, side, eps=EPS):
    """P displaced by eps/|w| to the side `side` (+1 = left) of the direction w."""
    n = (-w[1], w[0])
    nn = n[0] ** 2 + n[1] ** 2
    return (F(P[0]) + side * eps * F(n[0], nn), F(P[1]) + side * eps * F(n[1], nn))


def arc_points(P, w):
    return [P, (P[0] + w[0], P[1] + w[1])]


def arc(P, w):
    """The straight arc between the lattice points P and P + w."""
    return encode(arc_points(P, w))


def linear_loop_points(P, w, n, sides, eps=EPS, start=F(1, 3)):
    assert (n * w[0]) % 2 == 0 and (n * w[1]) % 2 == 0
    base = offset((P[0] + start * w[0], P[1] + start * w[1]), w, sides[1 % n], eps)
    pts = [base]
    for j in range(1, n + 1):
        pts.append(offset((P[0] + j * w[0], P[1] + j * w[1]), w, sides[j % n], eps))
    pts.append((base[0] + n * w[0], base[1] + n * w[1]))
    return pts


def linear_loop(P, w, n, sides, eps=EPS):
    """The closed linear curve whose lift follows the lattice line P + R w with period n w, passing the lattice
    point P + j w on the side sides[j mod n] (+1 = left of w)."""
    return encode(linear_loop_points(P, w, n, sides, eps), closed=True)


def figure8_points(P, w, eps=EPS):
    return linear_loop_points(P, w, 2, [+1, -1], eps)


def figure8(P, w, eps=EPS):
    """The figure-eight around the straight arc [P, P + w]: its lift weaves along the lattice line."""
    return linear_loop(P, w, 2, [+1, -1], eps)


def scc_points(w, off=F(1, 2)):
    n = (-w[1], w[0])
    nn = n[0] ** 2 + n[1] ** 2
    base = (off * F(n[0], nn) + F(1, 3) * w[0], off * F(n[1], nn) + F(1, 3) * w[1])
    return [base, (base[0] + w[0], base[1] + w[1]), (base[0] + 2 * w[0], base[1] + 2 * w[1])]


def scc(w, off=F(1, 2)):
    """The simple closed curve of direction w."""
    return encode(scc_points(w, off), closed=True)


def kink_vertex(prev, p, nxt, eps=EPS):
    """A vertex just outside a turn at the lattice point p (p inside the turn)."""
    a = (F(prev[0] - p[0]), F(prev[1] - p[1]))
    b = (F(nxt[0] - p[0]), F(nxt[1] - p[1]))
    na = abs(a[0]) + abs(a[1])
    nb = abs(b[0]) + abs(b[1])
    bis = (a[0] / na + b[0] / nb, a[1] / na + b[1] / nb)
    return (p[0] - eps * bis[0], p[1] - eps * bis[1])


# ----------------------------------------------------------------------------------------------- slopes and earrings

def direction(s):
    """The primitive direction w = (a, b) of the line of KWZ slope s = -a/b (s = None: infinity)."""
    if s is None:
        return (1, 0)
    a, b = -s.numerator, s.denominator
    if a < 0 or (a == 0 and b < 0):
        a, b = -a, -b
    return (a, b)


def line_base(w, avoid):
    """A lattice point P0 such that the lattice line P0 + Z w avoids the class `avoid` ('STAR' or 'P1')."""
    for P0 in ((0, 0), (1, 1), (1, 0), (0, 1)):
        c0, c1 = cls(P0), cls((P0[0] + w[0], P0[1] + w[1]))
        if avoid not in (c0, c1):
            return P0
    raise ValueError(w)


def earring_points(r):
    """Polyline of the earring curve E_r of Q^_r in Smith's coordinates (r = None: r = infinity): the figure-eight
    around the straight arc of Q_{-r} on the lattice line that avoids the corner (pi, pi)."""
    s = None if r is None else -r
    w = direction(s)
    return figure8_points(line_base(w, 'P1'), w)


def earring(r):
    return encode(earring_points(r), closed=True)


def kh_rational_points(x):
    """Polyline of Kotelskiy--Watson--Zibrowius's Kh~(Q_x) in their chart (corner (0, pi) special)."""
    w = direction(x)
    return figure8_points(line_base(w, 'STAR'), w)


def kh_rational(x):
    return encode(kh_rational_points(x), closed=True)


def bn_rational(x):
    """KWZ's BN~(Q_x): the straight arc on the lattice line of direction w(x) avoiding (0, pi)."""
    w = direction(x)
    return arc(line_base(w, 'STAR'), w)


def parity(r):
    """'odd/odd', 'even-den' or 'even-num' for the slope r = m/n (r = None counts as 1/0)."""
    if r is None:
        return 'even-den'
    p, q = r.numerator, r.denominator
    if p % 2 and q % 2:
        return 'odd/odd'
    if q % 2 == 0:
        return 'even-den'
    return 'even-num'


# ----------------------------------------------------------------------------------------------- the curves of Section 7.2

R0 = (1, -1)                       # a lift of the corner (0, 0)
CDIR = (-1, 1)                     # the direction of c (parallel to the arc of E_{-1})


def Mq(q):
    """The lift p_M of (pi, 0) at the other end of the lift [p_M, p_0] of alpha_q, p_0 = R0."""
    return (2 - q, 3 * q - 5)


def alpha_points(q):
    return [R0, Mq(q)]


def alpha(q):
    """alpha_q, the arc of E_{r_q}, r_q = (1 - q)/(3q - 4): the straight arc from (0, 0) to (pi, 0)."""
    return encode(alpha_points(q))


def c_points(periods=1):
    base = (F(1, 2) + F(1, 3) * CDIR[0], F(1, 3) * CDIR[1])
    return [base] + [(base[0] + 2 * k * CDIR[0], base[1] + 2 * k * CDIR[1]) for k in range(1, periods + 1)]


def c_curve(periods=1):
    """c (periods = 1) and its doubled word (periods = 2), which represents (c, J_2) over F2."""
    return encode(c_points(periods), closed=True)


def slide_points(start, corner, d, periods=2, side=-1):
    """start -> corner, turning around the lattice point `corner`, then along the lattice line of direction d for
    `periods` periods of c, passing the intermediate lattice points on the side `side` (+1 = left of d)."""
    nxt = (corner[0] + d[0], corner[1] + d[1])
    pts = [start, kink_vertex(start, corner, nxt)]
    n = 2 * periods
    for j in range(1, n):
        pts.append(offset((corner[0] + j * d[0], corner[1] + j * d[1]), d, side))
    pts.append((corner[0] + n * d[0], corner[1] + n * d[1]))
    return pts


def bn_kwz_points(q):
    """A polyline for KWZ's BN~(T_q) in their chart: alpha_q slid at its end over (pi, 0)."""
    return slide_points(R0, Mq(q), CDIR, 2, -1)


def bn_points(q):
    """BN_q = Phi(BN~(T_q)) in Smith's coordinates."""
    return shift(bn_kwz_points(q))


def bn_smith(q):
    return encode(bn_points(q))


def slides(q):
    """The 24 arcs obtained from alpha_q by sliding one end along c, in either direction and on either side, through
    one, two or three periods: {(end, direction, periods, side): object}."""
    out = {}
    for end in ('(0,0)', '(pi,0)'):
        start, corner = (Mq(q), R0) if end == '(0,0)' else (R0, Mq(q))
        for dname, d in (('+c', CDIR), ('-c', (-CDIR[0], -CDIR[1]))):
            for per in (1, 2, 3):
                for side in (-1, 1):
                    key = (end, dname, per, 'left' if side == 1 else 'right')
                    out[key] = encode(slide_points(start, corner, d, per, side))
    return out


# ----------------------------------------------------------------------------------------------- general linear curves

def side_patterns(n):
    import itertools
    seen, out = set(), []
    for p in itertools.product((1, -1), repeat=n):
        key = min(tuple(p[i:] + p[:i]) for i in range(n))
        if key in seen:
            continue
        seen.add(key)
        out.append(p)
    return out


def linear_test_curves(w, nmax=6):
    """All linear curves of direction w (Definition 7.4): on each of the two lattice lines of direction w, every side
    pattern of period 2, 4 or 6 (up to rotation, without repetitions of a shorter period), and the simple closed
    curve.  Returns a list of (label, object)."""
    out = []
    lines = {}
    for P0 in ((0, 0), (1, 0), (0, 1), (1, 1)):
        pair = frozenset((cls(P0), cls((P0[0] + w[0], P0[1] + w[1]))))
        lines.setdefault(pair, P0)
    for pair, P0 in lines.items():
        for n in range(2, nmax + 1, 2):
            for pat in side_patterns(n):
                if n > 2 and len(set(pat[i::2] for i in range(2))) == 1 and pat[:2] * (n // 2) == pat:
                    continue
                try:
                    obj = linear_loop(P0, w, n, list(pat))
                except AssertionError:
                    continue
                line = '-'.join(sorted(NAME[x] for x in pair))
                out.append(((line, n, pat), obj))
    out.append((('scc',), scc(w)))
    return out


def primitive_directions(B):
    return sorted({(a, b) for a in range(0, B + 1) for b in range(-B, B + 1)
                   if math.gcd(a, b) == 1 and (a > 0 or b == 1)}, key=lambda w: (abs(w[0]) + abs(w[1]), w))
